### PR TITLE
shell.nix: Set correct editable sources names

### PR DESCRIPTION
**Pull request by adisbladis**
###  :notebook_with_decorative_cover: Description

Poetry2nix normalises names internally, and these are the names that are set in the respective `pyproject.toml` files.

This PR also depends on https://github.com/nix-community/poetry2nix/pull/486.

###  :memo: Checklist

- [ ] All user-facing changes have changelog entries.
- [ ] The changes are reflected on [docs.tenzir.com/threatbus](https://docs.tenzir.com/threatbus), if necessary.
- [ ] The PR description contains instructions for the reviewer, if necessary.

### CODE REVIEW

**Comment by tobim** [comment]
Thanks. I'm going to check if https://github.com/nix-community/poetry2nix/issues/307 is solved with the changes here.

**Review by tobim — APPROVED** [review]
I was able to get a working python environment by integrating https://github.com/nix-community/poetry2nix/pull/486 into a local copy of nixpkgs and running `nix-shell -I nixpkgs=/path/to/modified/nixpkgs`.

**Comment by tobim** [comment]
@adisbladis can you either sign and re-upload your commit or check "Allow edits from maintainers"?

**Comment by adisbladis** [comment]
"Allow edits from maintainers" is already checked.

**Comment by adisbladis** [comment]
FYI with the latest master of poetry2nix you could also remove the editable sources section from the Nix expression: https://github.com/nix-community/poetry2nix/pull/487.

**Pull request merged**
