### PR TITLE
Use pip to install packages

### PR DESCRIPTION
**Pull request by 0ortmann**
###  :notebook_with_decorative_cover: Description

This fixes the Docker build.

###  :memo: Checklist

- [x] All user-facing changes have changelog entries.
- [x] The changes are reflected on [docs.tenzir.com/threatbus](https://docs.tenzir.com/threatbus), if necessary.
- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

```
cp config.yaml.example config.yaml  
docker build . -t tb
docker run --net=host -ti tb
```
It will behave like a normal process, can be terminated with `ctrl+c` and updates logs to the terminal when you send around messages. The `--net=host` makes it work with locally installed software like misp, cif, or vast.

### CODE REVIEW

**Comment by lava** [comment]
I tried to follow the review instructions, but ran into the following error in the final step:
```
$ sudo docker run --net=host -ti tb
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/confuse/yaml_util.py", line 85, in load_yaml
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/tenzir/threatbus/config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/threatbus", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/threatbus/threatbus.py", line 200, in main
    config.set_file(args.config)
  File "/usr/local/lib/python3.7/dist-packages/confuse/core.py", line 637, in set_file
    self.set(YamlSource(filename, loader=self.loader))
  File "/usr/local/lib/python3.7/dist-packages/confuse/sources.py", line 58, in __init__
    self.load()
  File "/usr/local/lib/python3.7/dist-packages/confuse/sources.py", line 67, in load
    loader=self.loader) or {}
  File "/usr/local/lib/python3.7/dist-packages/confuse/yaml_util.py", line 88, in load_yaml
    raise ConfigReadError(filename, exc)
confuse.exceptions.ConfigReadError: file /opt/tenzir/threatbus/config.yaml could not be read: [Errno 2] No such file or directory: '/opt/tenzir/threatbus/config.yaml'
```

**Comment by 0ortmann** [comment]
@lava I updated the installation instructions. The config file was missing. I also used this branch to pin a dependency version that has a bug in latest (pymisp). Could you please pull and retry?

**Review by lava — APPROVED** [review]
There are still quite a few errors when starting the container, but I assume these other components should have been set up on my local machine, outside the threatbus container?

```
benno@poincare:~/src/threatbus$ sudo docker run --net=host -ti tb
2020-11-24 15:18:07 INFO     [threatbus] Disabling installed, but unconfigured backbones 'inmem'
2020-11-24 15:18:07 INFO     [threatbus] Starting plugins...
2020-11-24 15:18:07 DEBUG    [threatbus_rabbitmq.plugin] RabbitMQ consumer: connecting...
2020-11-24 15:18:07 DEBUG    [threatbus_rabbitmq.plugin] RabbitMQ publisher: connecting...
2020-11-24 15:18:07 INFO     [threatbus_rabbitmq.plugin] RabbitMQ backbone started.
2020-11-24 15:18:07 INFO     [threatbus_rabbitmq.plugin] Adding subscription to: threatbus/snapshotrequest
2020-11-24 15:18:07 INFO     [threatbus_rabbitmq.plugin] Adding subscription to: threatbus/snapshotenvelope
2020-11-24 15:18:07 ERROR    [threatbus_misp.plugin] Cannot subscribe to MISP at https://localhost, using SSL: False
2020-11-24 15:18:07 ERROR    [threatbus_misp.plugin] Failed to start MISP plugin
2020-11-24 15:18:08 ERROR    [threatbus_rabbitmq.plugin] RabbitMQ consumer: connection failed to open 
2020-11-24 15:18:08 INFO     [threatbus_zmq_app.plugin] ZeroMQ app plugin started
2020-11-24 15:18:08 ERROR    [threatbus_rabbitmq.plugin] RabbitMQ publisher: connection failed to open.
2020-11-24 15:18:08 ERROR    [threatbus_cif3.plugin] Cannot connect to CIFv3 at http://localhost:5000, using SSL: False. Exiting plugin. HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35e1eea320>: Failed to establish a new connection: [Errno 111] Connection refused'))
2020-11-24 15:18:08 INFO     [threatbus_zeek.plugin] Zeek plugin started
```

Apart from this, looks good to me.

**Comment by 0ortmann** [comment]
Yes, correct. The config activates almost all plugins and hence tries to connect to a bunch of systems. The error messages tell us that these configured endpoints don't exist. The important bit is that Threat Bus and plugins come up correctly.

**Pull request merged**
